In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#import du fichier CSV Mapping_Distance.csv

Mapping_Distance = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Mapping_Distance.csv',decimal=".")

Mapping_Distance.head()

,Unnamed: 0,Zone,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No),Distance_Economique Pays_France(Km)
0,0,Aruba,ABW,533.0,22.0,NaN,NaN,NaN,16.50,NaN,7711.830
1,1,Afghanistan,AFG,4.0,2.0,5.0,254.0,-103.185185,78.88,1185.84,5489.888
2,2,Angola,AGO,24.0,7.0,35.0,5873.0,277.000000,87.92,5998.46,6363.600
3,3,Anguilla,AIA,660.0,258.0,NaN,NaN,NaN,30.92,NaN,6737.844
4,4,Albania,ALB,8.0,3.0,85.0,438.0,38.000000,-7.88,421.64,1461.321

In [ ]:
#import du fichier CSV Stabilite_Politique.csv

Stabilite_Politique = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Stabilite_Politique.csv',decimal=".")

Stabilite_Politique.head()

             Zone Country Code  indice_stabilite
0     Afghanistan          AFG             -2.48
1         Albania          ALB              0.18
2         Algeria          DZA             -0.58
3  American Samoa          ASM              1.11
4         Andorra          AND              1.58

In [ ]:
# jointure des 2 dataframes sur 2 colonnes Country Code

Mapping_Politique = Mapping_Distance.merge(Stabilite_Politique, on=["Country Code"], how='outer')
display(Mapping_Politique)

,Unnamed: 0,Zone_x,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No),Distance_Economique Pays_France(Km),Zone_y,indice_stabilite
0,0,Aruba,ABW,533.0,22.0,NaN,NaN,NaN,16.50,NaN,7711.830,Aruba,1.43
1,1,Afghanistan,AFG,4.0,2.0,5.0,254.0,-103.185185,78.88,1185.84,5489.888,Afghanistan,-2.48
2,2,Angola,AGO,24.0,7.0,35.0,5873.0,277.000000,87.92,5998.46,6363.600,Angola,-0.34
3,3,Anguilla,AIA,660.0,258.0,NaN,NaN,NaN,30.92,NaN,6737.844,Anguilla,1.11
4,4,Albania,ALB,8.0,3.0,85.0,438.0,38.000000,-7.88,421.64,1461.321,Albania,0.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,243,Kosovo,XKX,983.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,Kosovo,-0.32
241,244,Yemen,YEM,887.0,249.0,30.0,282.0,78.000000,63.70,NaN,5235.171,"Yemen, Rep.",-2.56
242,246,South Africa,ZAF,710.0,202.0,143.0,5357.0,451.000000,28.52,931.43,8750.608,South Africa,-0.67
243,248,Zambia,ZMB,894.0,251.0,11.0,551.0,11.000000,66.59,3653.36,7221.197,Zambia,0.20
244,249,Zimbabwe,ZWE,716.0,181.0,16.0,44.0,-126.185185,21.52,3041.81,7759.680,Zimbabwe,-0.93

In [ ]:
#Suppression de la colonne Unnamed: 0
Mapping_Politique = Mapping_Politique.drop('Unnamed: 0', axis=1)
Mapping_Politique.head()

,Zone_x,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No),Distance_Economique Pays_France(Km),Zone_y,indice_stabilite
0,Aruba,ABW,533.0,22.0,NaN,NaN,NaN,16.50,NaN,7711.830,Aruba,1.43
1,Afghanistan,AFG,4.0,2.0,5.0,254.0,-103.185185,78.88,1185.84,5489.888,Afghanistan,-2.48
2,Angola,AGO,24.0,7.0,35.0,5873.0,277.000000,87.92,5998.46,6363.600,Angola,-0.34
3,Anguilla,AIA,660.0,258.0,NaN,NaN,NaN,30.92,NaN,6737.844,Anguilla,1.11
4,Albania,ALB,8.0,3.0,85.0,438.0,38.000000,-7.88,421.64,1461.321,Albania,0.18

In [ ]:
#vérification des valeurs manquantes
print(Mapping_Politique.isnull().sum())

Zone_x                                                    0
Country Code                                              0
Numeric                                                   0
Code zone                                                 4
Disponibilité alimentaire (Kcal/personne/jour)           73
Quantité Aliments_disponible Poules(Milliers tonnes)     71
Export_Utile(Milliers tonnes)                            73
Taux de croissance_population [%]                         9
Emploi dans la production_vegetale_animale (1000No)     103
Distance_Economique Pays_France(Km)                      19
Zone_y                                                   29
indice_stabilite                                         30
dtype: int64

In [ ]:
#Suppression de la colonne Zone_y
Mapping_Politique = Mapping_Politique.drop('Zone_y', axis=1)

In [ ]:
# Renommage des colonnes de Zone_x
Mapping_Politique = Mapping_Politique.rename(columns={'Zone_x': 'Zone'})
Mapping_Politique.head()

,Zone,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No),Distance_Economique Pays_France(Km),indice_stabilite
0,Aruba,ABW,533.0,22.0,NaN,NaN,NaN,16.50,NaN,7711.830,1.43
1,Afghanistan,AFG,4.0,2.0,5.0,254.0,-103.185185,78.88,1185.84,5489.888,-2.48
2,Angola,AGO,24.0,7.0,35.0,5873.0,277.000000,87.92,5998.46,6363.600,-0.34
3,Anguilla,AIA,660.0,258.0,NaN,NaN,NaN,30.92,NaN,6737.844,1.11
4,Albania,ALB,8.0,3.0,85.0,438.0,38.000000,-7.88,421.64,1461.321,0.18

In [ ]:
Mapping_Politique.shape

(245, 11)

In [ ]:
#préparation de l'export du dataframe en fichier CSV

Mapping_Politique.to_csv('/content/drive/MyDrive/Colab Notebooks/Mapping_Politique.csv')