In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#import du fichier CSV Mapping_PIB.csv

Mapping_PIB = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Mapping_PIB.csv',decimal=".")

Mapping_PIB.head()

,Unnamed: 0,Zone,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No),Distance_Economique Pays_France(Km),Indice Stabilite Politique,Croissance du PIB % annuel
0,0,Aruba,ABW,533.0,22.0,NaN,NaN,NaN,16.50,NaN,7711.830,1.43,4.26
1,1,Afghanistan,AFG,4.0,2.0,5.0,254.0,-103.185185,78.88,1185.84,5489.888,-2.48,2.27
2,2,Angola,AGO,24.0,7.0,35.0,5873.0,277.000000,87.92,5998.46,6363.600,-0.34,4.42
3,3,Anguilla,AIA,660.0,258.0,NaN,NaN,NaN,30.92,NaN,6737.844,1.11,NaN
4,4,Albania,ALB,8.0,3.0,85.0,438.0,38.000000,-7.88,421.64,1461.321,0.18,3.96

In [ ]:
#import du fichier CSV Qualite_Reglementaire.csv

data_qualite_reglementaire = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Qualite_Reglementaire.csv',decimal=".")

data_qualite_reglementaire.head()

             Zone Country Code  qualite_reglementaire
0     Afghanistan          AFG                  -1.27
1         Albania          ALB                   0.17
2         Algeria          DZA                  -0.95
3  American Samoa          ASM                   0.51
4         Andorra          AND                   1.35

In [ ]:
# jointure des 2 dataframes sur  colonnes Country Code

Mapping_Qualite = Mapping_PIB.merge(data_qualite_reglementaire, on=["Country Code"], how='outer')
display(Mapping_Qualite)

,Unnamed: 0,Zone_x,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No),Distance_Economique Pays_France(Km),Indice Stabilite Politique,Croissance du PIB % annuel,Zone_y,qualite_reglementaire
0,0,Aruba,ABW,533.0,22.0,NaN,NaN,NaN,16.50,NaN,7711.830,1.43,4.26,Aruba,0.95
1,1,Afghanistan,AFG,4.0,2.0,5.0,254.0,-103.185185,78.88,1185.84,5489.888,-2.48,2.27,Afghanistan,-1.27
2,2,Angola,AGO,24.0,7.0,35.0,5873.0,277.000000,87.92,5998.46,6363.600,-0.34,4.42,Angola,-0.76
3,3,Anguilla,AIA,660.0,258.0,NaN,NaN,NaN,30.92,NaN,6737.844,1.11,NaN,NaN,NaN
4,4,Albania,ALB,8.0,3.0,85.0,438.0,38.000000,-7.88,421.64,1461.321,0.18,3.96,Albania,0.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,240,Kosovo,XKX,983.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.32,4.41,Kosovo,-0.30
241,241,Yemen,YEM,887.0,249.0,30.0,282.0,78.000000,63.70,NaN,5235.171,-2.56,0.75,"Yemen, Rep.",-1.84
242,242,South Africa,ZAF,710.0,202.0,143.0,5357.0,451.000000,28.52,931.43,8750.608,-0.67,0.58,South Africa,-0.22
243,243,Zambia,ZMB,894.0,251.0,11.0,551.0,11.000000,66.59,3653.36,7221.197,0.20,4.04,Zambia,-0.50
244,244,Zimbabwe,ZWE,716.0,181.0,16.0,44.0,-126.185185,21.52,3041.81,7759.680,-0.93,2.03,Zimbabwe,-1.34

In [ ]:
#Suppression de la colonne Unnamed: 0
Mapping_Qualite = Mapping_Qualite.drop('Unnamed: 0', axis=1)

In [ ]:
#vérification des valeurs manquantes
print(Mapping_Qualite.isnull().sum())

Zone_x                                                    0
Country Code                                              0
Numeric                                                   0
Code zone                                                 4
Disponibilité alimentaire (Kcal/personne/jour)           73
Quantité Aliments_disponible Poules(Milliers tonnes)     71
Export_Utile(Milliers tonnes)                            73
Taux de croissance_population [%]                         9
Emploi dans la production_vegetale_animale (1000No)     103
Distance_Economique Pays_France(Km)                      19
Indice Stabilite Politique                               30
Croissance du PIB % annuel                               29
Zone_y                                                   26
qualite_reglementaire                                    38
dtype: int64

In [ ]:
#Suppression de la colonne Zone_y
Mapping_Qualite = Mapping_Qualite.drop('Zone_y', axis=1)

In [ ]:
# Renommage des colonnes de Zone_x
Mapping_Qualite = Mapping_Qualite.rename(columns={'Zone_x': 'Zone'})
Mapping_Qualite.head()

,Zone,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No),Distance_Economique Pays_France(Km),Indice Stabilite Politique,Croissance du PIB % annuel,qualite_reglementaire
0,Aruba,ABW,533.0,22.0,NaN,NaN,NaN,16.50,NaN,7711.830,1.43,4.26,0.95
1,Afghanistan,AFG,4.0,2.0,5.0,254.0,-103.185185,78.88,1185.84,5489.888,-2.48,2.27,-1.27
2,Angola,AGO,24.0,7.0,35.0,5873.0,277.000000,87.92,5998.46,6363.600,-0.34,4.42,-0.76
3,Anguilla,AIA,660.0,258.0,NaN,NaN,NaN,30.92,NaN,6737.844,1.11,NaN,NaN
4,Albania,ALB,8.0,3.0,85.0,438.0,38.000000,-7.88,421.64,1461.321,0.18,3.96,0.17

In [ ]:
#Renommage des colonnes--> plus propre

Mapping_Qualite = Mapping_Qualite.rename(columns={'qualite_reglementaire':'Qualité Reglementaire [-2,5..+2,5]'})
Mapping_Qualite.head()

,Zone,Country Code,Numeric,Code zone,Disponibilité alimentaire (Kcal/personne/jour),Quantité Aliments_disponible Poules(Milliers tonnes),Export_Utile(Milliers tonnes),Taux de croissance_population [%],Emploi dans la production_vegetale_animale (1000No),Distance_Economique Pays_France(Km),Indice Stabilite Politique,Croissance du PIB % annuel,"Qualité Reglementaire [-2,5..+2,5]"
0,Aruba,ABW,533.0,22.0,NaN,NaN,NaN,16.50,NaN,7711.830,1.43,4.26,0.95
1,Afghanistan,AFG,4.0,2.0,5.0,254.0,-103.185185,78.88,1185.84,5489.888,-2.48,2.27,-1.27
2,Angola,AGO,24.0,7.0,35.0,5873.0,277.000000,87.92,5998.46,6363.600,-0.34,4.42,-0.76
3,Anguilla,AIA,660.0,258.0,NaN,NaN,NaN,30.92,NaN,6737.844,1.11,NaN,NaN
4,Albania,ALB,8.0,3.0,85.0,438.0,38.000000,-7.88,421.64,1461.321,0.18,3.96,0.17

In [ ]:
Mapping_Qualite.shape

(245, 13)

In [ ]:
#préparation de l'export du dataframe en fichier CSV

Mapping_Qualite.to_csv('/content/drive/MyDrive/Colab Notebooks/Mapping_Qualite.csv')