In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Lecture du fichier Indicateur de la distance entre les pays
#La base de données (dist_cepii) est dyadique, c'est-à-dire qu'elle inclut des variables définies au niveau des paires de pays. La distance géographique est l'exemple le plus classique de ces variables,
#et le fichier inclut différentes mesures de distance bilatérales (en km) pour la plupart des paires de pays du monde.
df_dist_pays = pd.read_excel('/content/drive/MyDrive/Colab_Projet_Poule/dist_cepii.xls')
df_dist_pays.head()

,iso_o,iso_d,contig,comlang_off,comlang_ethno,colony,comcol,curcol,col45,smctry,dist,distcap,distw,distwces
0,ABW,ABW,0,0,0,0,0,0,0,0,5.225315,5.225315,25.09354,23.04723
1,ABW,AFG,0,0,0,0,0,0,0,0,13257.810000,13257.810000,13168.22,13166.37
2,ABW,AGO,0,0,0,0,0,0,0,0,9516.913000,9516.913000,9587.316,9584.193
3,ABW,AIA,0,0,1,0,0,0,0,0,983.268200,983.268200,976.8974,976.8916
4,ABW,ALB,0,0,0,0,0,0,0,0,9091.742000,9091.742000,9091.576,9091.466

In [ ]:
# Filtrer France (code ISO3 = 'FRA')
france_dist = df_dist_pays[df_dist_pays['iso_o'] == 'FRA'][['iso_o', 'iso_d', 'dist', 'distcap', 'distw','contig','distwces']]
france_dist.head()

      iso_o iso_d      dist   distcap     distw  contig  distwces
15008   FRA   ABW  7685.884  7685.884  7716.752       0   7711.83
15009   FRA   AFG  5590.381  5590.381  5500.665       0  5489.888
15010   FRA   AGO  6510.322  6510.322  6384.805       0    6363.6
15011   FRA   AIA  6710.570  6710.570  6743.427       0  6737.844
15012   FRA   ALB  1603.534  1603.534  1499.451       0  1461.321

In [ ]:
france_dist.shape

(224, 7)

In [ ]:
france_dist = france_dist.rename(columns={'iso_d': 'Country Code', 'dist': 'distance_simple',
                                         'distcap': 'distance_capitales', 'distw': 'Distance_ponderee Pays_France(Km)','distwces':'Distance_Economique Pays_France(Km)'})
print(france_dist.head())

      iso_o Country Code  distance_simple  distance_capitales  \
15008   FRA          ABW         7685.884            7685.884
15009   FRA          AFG         5590.381            5590.381
15010   FRA          AGO         6510.322            6510.322
15011   FRA          AIA         6710.570            6710.570
15012   FRA          ALB         1603.534            1603.534

      Distance_ponderee Pays_France(Km)  contig  \
15008                          7716.752       0
15009                          5500.665       0
15010                          6384.805       0
15011                          6743.427       0
15012                          1499.451       0

      Distance_Economique Pays_France(Km)
15008                             7711.83
15009                            5489.888
15010                              6363.6
15011                            6737.844
15012                            1461.321

In [ ]:
print(france_dist.loc[france_dist['Country Code']== 'CCK'])

      iso_o Country Code  distance_simple  distance_capitales  \
15042   FRA          CCK         11388.36            11388.36

      Distance_ponderee Pays_France(Km)  contig  \
15042                                 .       0

      Distance_Economique Pays_France(Km)
15042                                   .

In [ ]:
#Filtrer pour les variables Country Code et distance_ponderee
var_distance = ['Country Code','Distance_ponderee Pays_France(Km)','Distance_Economique Pays_France(Km)']
france_dist = france_dist[var_distance]
#france_dist.reset_index(inplace=True)
france_dist.head()

,Country Code,Distance_ponderee Pays_France(Km),Distance_Economique Pays_France(Km)
15008,ABW,7716.752,7711.83
15009,AFG,5500.665,5489.888
15010,AGO,6384.805,6363.6
15011,AIA,6743.427,6737.844
15012,ALB,1499.451,1461.321

In [ ]:
#vérification des valeurs manquantes
print(france_dist.isnull().sum())

Country Code                           0
Distance_ponderee Pays_France(Km)      0
Distance_Economique Pays_France(Km)    0
dtype: int64

In [ ]:
#Vérification des Doublons
france_dist.loc[france_dist[['Country Code','Distance_ponderee Pays_France(Km)','Distance_Economique Pays_France(Km)']].duplicated(keep=False),:]

Empty DataFrame
Columns: [Country Code, Distance_ponderee Pays_France(Km), Distance_Economique Pays_France(Km)]
Index: []

In [ ]:
#Verification de type des variables
france_dist.dtypes

Country Code                           object
Distance_ponderee Pays_France(Km)      object
Distance_Economique Pays_France(Km)    object
dtype: object

In [ ]:
#Conversion du type de la varible d'object à float
france_dist_num = france_dist
france_dist_num['Distance_ponderee Pays_France(Km)'] = pd.to_numeric(france_dist_num['Distance_ponderee Pays_France(Km)'], errors='coerce')

In [ ]:

france_dist_num['Distance_Economique Pays_France(Km)'] = pd.to_numeric(france_dist_num['Distance_Economique Pays_France(Km)'], errors='coerce')

In [ ]:
france_dist_num.head()

,Country Code,Distance_ponderee Pays_France(Km),Distance_Economique Pays_France(Km)
15008,ABW,7716.752,7711.830
15009,AFG,5500.665,5489.888
15010,AGO,6384.805,6363.600
15011,AIA,6743.427,6737.844
15012,ALB,1499.451,1461.321

In [ ]:
#Verification de type des variables
france_dist_num.dtypes

Country Code                            object
Distance_ponderee Pays_France(Km)      float64
Distance_Economique Pays_France(Km)    float64
dtype: object

In [ ]:
#vérification des valeurs manquantes
print(france_dist_num.isnull().sum())

Country Code                           0
Distance_ponderee Pays_France(Km)      5
Distance_Economique Pays_France(Km)    5
dtype: int64

In [ ]:
#Détail des valeurs manquantes pour la distance_ponderee entre Pays_France(Km)
france_dist_num.loc[france_dist_num['Distance_ponderee Pays_France(Km)'].isnull(),:]

,Country Code,Distance_ponderee Pays_France(Km),Distance_Economique Pays_France(Km)
15042,CCK,NaN,NaN
15055,CXR,NaN,NaN
15128,MAC,NaN,NaN
15143,MSR,NaN,NaN
15164,PCN,NaN,NaN

In [ ]:
france_dist_num.loc[15042,'Distance_ponderee Pays_France(Km)']= 11388.36
france_dist_num.loc[15042,'Distance_Economique Pays_France(Km)']= 11388.36
france_dist_num.loc[15042]

Country Code                                CCK
Distance_ponderee Pays_France(Km)      11388.36
Distance_Economique Pays_France(Km)    11388.36
Name: 15042, dtype: object

In [ ]:
france_dist_num.loc[15055,'Distance_ponderee Pays_France(Km)']= 11866.1
france_dist_num.loc[15055,'Distance_Economique Pays_France(Km)']= 11866.1
france_dist_num.loc[15055]

Country Code                               CXR
Distance_ponderee Pays_France(Km)      11866.1
Distance_Economique Pays_France(Km)    11866.1
Name: 15055, dtype: object

In [ ]:
france_dist_num.loc[15128,'Distance_ponderee Pays_France(Km)']= 9601.923
france_dist_num.loc[15128,'Distance_Economique Pays_France(Km)']= 9601.923
france_dist_num.loc[15128]

Country Code                                MAC
Distance_ponderee Pays_France(Km)      9601.923
Distance_Economique Pays_France(Km)    9601.923
Name: 15128, dtype: object

In [ ]:
france_dist_num.loc[15143,'Distance_ponderee Pays_France(Km)']= 6771.885
france_dist_num.loc[15143,'Distance_Economique Pays_France(Km)']= 6771.885
france_dist_num.loc[15143]

Country Code                                MSR
Distance_ponderee Pays_France(Km)      6771.885
Distance_Economique Pays_France(Km)    6771.885
Name: 15143, dtype: object

In [ ]:
france_dist_num.loc[15164,'Distance_ponderee Pays_France(Km)']= 15152.12
france_dist_num.loc[15164,'Distance_Economique Pays_France(Km)']= 15152.12
france_dist_num.loc[15164]

Country Code                                PCN
Distance_ponderee Pays_France(Km)      15152.12
Distance_Economique Pays_France(Km)    15152.12
Name: 15164, dtype: object

In [ ]:
#Verification s'il y a des outliers
france_dist_num.describe()

       Distance_ponderee Pays_France(Km)  Distance_Economique Pays_France(Km)
count                         224.000000                           224.000000
mean                         6651.284712                          6624.865781
std                          4282.389267                          4299.975705
min                           408.960300                           161.405800
25%                          3389.659500                          3355.571500
50%                          6596.657500                          6548.592000
75%                          8868.157000                          8862.506750
max                         18894.290000                         18890.980000

In [ ]:
#vérification des valeurs manquantes
print(france_dist_num.isnull().sum())

Country Code                           0
Distance_ponderee Pays_France(Km)      0
Distance_Economique Pays_France(Km)    0
dtype: int64

In [ ]:
#Vérification des Doublons
france_dist_num.loc[france_dist_num[['Country Code','Distance_ponderee Pays_France(Km)','Distance_Economique Pays_France(Km)']].duplicated(keep=False),:]

Empty DataFrame
Columns: [Country Code, Distance_ponderee Pays_France(Km), Distance_Economique Pays_France(Km)]
Index: []

In [ ]:
# Affichage du Dataframe

display(france_dist_num)

,Country Code,Distance_ponderee Pays_France(Km),Distance_Economique Pays_France(Km)
15008,ABW,7716.752,7711.830
15009,AFG,5500.665,5489.888
15010,AGO,6384.805,6363.600
15011,AIA,6743.427,6737.844
15012,ALB,1499.451,1461.321
...,...,...,...
15227,YUG,1429.045,1397.047
15228,ZAF,8769.679,8750.608
15229,ZAR,6036.588,5995.903
15230,ZMB,7236.737,7221.197
15231,ZWE,7771.569,7759.680

In [ ]:
#Garder que la variable Distance_Economique Pays_France(Km)
var_dist = ['Country Code','Distance_Economique Pays_France(Km)']

france_dist_eco = france_dist_num[var_dist]
france_dist_eco.reset_index(drop=True, inplace=True)
france_dist_eco.head()

  Country Code  Distance_Economique Pays_France(Km)
0          ABW                             7711.830
1          AFG                             5489.888
2          AGO                             6363.600
3          AIA                             6737.844
4          ALB                             1461.321

In [ ]:
#préparation de l'export du dataframe en fichier CSV

france_dist_eco.to_csv('/content/drive/MyDrive/Colab Notebooks/france_dist_eco.csv', index=False)