In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
# Lecture du fichioer Indice_PIB.csv
#Exploitation de la richesse créée dans une économie au cours d'une année par l'étude de l'indicateur PIB (Produit Intérieur Brut)
data_PIB = pd.read_csv('/content/drive/MyDrive/Colab_Projet_Poule/Indice_PIB.csv')
data_PIB.head()

,Series Name,Series Code,Country Name,Country Code,1990 [YR1990],2000 [YR2000],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,Afghanistan,AFG,..,..,1.45131466066431,2.26031420279821,2.6470032027451,1.18922812944517,3.91160341625552,-2.35110067203466,-20.7388393676343,-6.24017199240269,2.26694373649188,..
1,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,Albania,ALB,-9.57564016993408,7.46285871776054,2.2277040745779,3.90893551362245,3.28317593330073,3.67141928098908,2.06257790176122,-3.31375636888916,8.96957619074095,4.82669611912765,3.93661689192599,3.96171911223713
2,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,Algeria,DZA,0.800000580174981,3.80000000158476,3.20000000089023,3.90000000017621,1.49999999895587,1.40000000088281,0.899999999219148,-4.99999999908597,3.79999999900707,3.60000000094915,4.10000000005964,3.29999999939609
3,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,American Samoa,ASM,..,..,3.14960629921259,-1.67938931297709,-6.98757763975155,2.6711185308848,-0.487804878048777,4.41176470588236,-0.782472613458523,1.73501577287065,..,..
4,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,Andorra,AND,3.78138754899436,3.52836236122388,1.43414039522716,3.70967806978986,0.346071889630295,1.58876549046354,2.01554763848308,-11.1839399355384,8.28677879049404,9.56461225648184,2.58355480961319,3.37182032638998

In [6]:
#Verification de type des variables
data_PIB.dtypes

Series Name      object
Series Code      object
Country Name     object
Country Code     object
1990 [YR1990]    object
2000 [YR2000]    object
2015 [YR2015]    object
2016 [YR2016]    object
2017 [YR2017]    object
2018 [YR2018]    object
2019 [YR2019]    object
2020 [YR2020]    object
2021 [YR2021]    object
2022 [YR2022]    object
2023 [YR2023]    object
2024 [YR2024]    object
dtype: object

In [7]:
#vérification des valeurs manquantes
print(data_PIB.isnull().sum())

Series Name      3
Series Code      5
Country Name     5
Country Code     5
1990 [YR1990]    5
2000 [YR2000]    5
2015 [YR2015]    5
2016 [YR2016]    5
2017 [YR2017]    5
2018 [YR2018]    5
2019 [YR2019]    5
2020 [YR2020]    5
2021 [YR2021]    5
2022 [YR2022]    5
2023 [YR2023]    5
2024 [YR2024]    5
dtype: int64

In [8]:
#Détail des valeurs manquantes pour la Country Name
data_PIB.loc[data_PIB['Country Name'].isnull(),:]

,Series Name,Series Code,Country Name,Country Code,1990 [YR1990],2000 [YR2000],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,Last Updated: 10/07/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#Suppression des lignes ayant Country Name null
data_PIB = data_PIB.drop(index=[266,267,268,269,270])

In [10]:
#vérification des valeurs manquantes
print(data_PIB.isnull().sum())

Series Name      0
Series Code      0
Country Name     0
Country Code     0
1990 [YR1990]    0
2000 [YR2000]    0
2015 [YR2015]    0
2016 [YR2016]    0
2017 [YR2017]    0
2018 [YR2018]    0
2019 [YR2019]    0
2020 [YR2020]    0
2021 [YR2021]    0
2022 [YR2022]    0
2023 [YR2023]    0
2024 [YR2024]    0
dtype: int64

In [11]:
import re

#Copie du dataframe data_PIB
data_index_PIB = data_PIB.copy()

#détecter les colonnes année (ex : 2000 [YR2000])
year_cols = [c for c in data_index_PIB.columns if re.search(r'\b\d{4}\b', str(c))]
pd.set_option('future.no_silent_downcasting', True)
#normaliser placeholders en NaN (ex: '..', '', 'NA')
data_index_PIB[year_cols] = data_index_PIB[year_cols].replace(['..', '', 'NA', 'na', 'N/A'], np.nan)

In [12]:
import sys
sys.path.append('/content/drive/MyDrive/Colab Notebooks')

In [13]:
import importlib
import Parcourir

importlib.reload(Parcourir)

In [14]:
 #remplissage des valeurs .. en 2024 par la valeur la plus récente
data_index_PIB['2024 [YR2024]'] = data_index_PIB[year_cols].apply(Parcourir.last_valid_value_from_right, axis=1)

In [15]:
#Nouvelle variable indice_PIB pour l'année 2024
data_index_PIB['indice_PIB'] = data_index_PIB['2024 [YR2024]']

# Conversion de la colonne indice_PIB en numerique
data_index_PIB['indice_PIB'] = pd.to_numeric(data_index_PIB['indice_PIB'], errors='coerce')

# Arrondi des valeurs de l'indice_PIB à 2 décimales
data_index_PIB['indice_PIB'] = round(data_index_PIB['indice_PIB'], 2)

# Renommage des colonnes
data_index_PIB = data_index_PIB.rename(columns={'Country Name': 'Zone'})

#nouveau dataframe avec 3 variable : Zone, Country Code et indice_PIB
variables_PIB = ['Zone','Country Code','indice_PIB']
data_index_PIB = data_index_PIB[variables_PIB]
display(data_index_PIB)

                                           Zone Country Code  indice_PIB
0                                   Afghanistan          AFG        2.27
1                                       Albania          ALB        3.96
2                                       Algeria          DZA        3.30
3                                American Samoa          ASM        1.74
4                                       Andorra          AND        3.37
..                                          ...          ...         ...
261                          Sub-Saharan Africa          SSF        3.43
262  Sub-Saharan Africa (excluding high income)          SSA        3.20
263   Sub-Saharan Africa (IDA & IBRD countries)          TSS        3.43
264                         Upper middle income          UMC        4.15
265                                       World          WLD        2.86

[266 rows x 3 columns]

In [16]:
#Suppression des lignes qui représente des zones géographique non des pays
data_index_PIB = data_index_PIB.drop(data_index_PIB.index[217:266])
display(data_index_PIB)

                      Zone Country Code  indice_PIB
0              Afghanistan          AFG        2.27
1                  Albania          ALB        3.96
2                  Algeria          DZA        3.30
3           American Samoa          ASM        1.74
4                  Andorra          AND        3.37
..                     ...          ...         ...
212  Virgin Islands (U.S.)          VIR       -1.31
213     West Bank and Gaza          PSE      -26.56
214            Yemen, Rep.          YEM        0.75
215                 Zambia          ZMB        4.04
216               Zimbabwe          ZWE        2.03

[217 rows x 3 columns]

In [17]:
#vérification des valeurs manquantes
print(data_index_PIB.isnull().sum())

Zone            0
Country Code    0
indice_PIB      3
dtype: int64

In [18]:
#préparation de l'export du dataframe en fichier CSV

data_index_PIB.to_csv('/content/drive/MyDrive/Colab Notebooks/data_index_PIB.csv', index=False)