In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# Lecture du fichioer Stabilite_Politique.csv
data_stability = pd.read_csv('/content/drive/MyDrive/Colab_Projet_Poule/Stabilite_Politique.csv')
data_stability.head()

,Series Name,Series Code,Country Name,Country Code,2000 [YR2000],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Political Stability and Absence of Violence/Te...,PV.EST,Afghanistan,AFG,-2.43896889686584,-2.41106843948364,-2.56262516975403,-2.6621561050415,-2.7949755191803,-2.75344133377075,-2.65253973007202,-2.702721118927,-2.51867604255676,-2.54495596885681,-2.48408055305481
1,Political Stability and Absence of Violence/Te...,PV.EST,Albania,ALB,-0.539989590644836,0.485986232757568,0.341639041900635,0.337447881698608,0.373770743608475,0.366779267787933,0.11010505259037,0.0886125192046165,0.196371927857399,0.106261312961578,0.183348968625069
2,Political Stability and Absence of Violence/Te...,PV.EST,Algeria,DZA,-1.43257737159729,-1.19053518772125,-1.09078657627106,-1.09974193572998,-0.919614315032959,-0.842107713222504,-1.05585384368896,-0.847820401191711,-0.992457151412964,-0.650652348995209,-0.577885270118713
3,Political Stability and Absence of Violence/Te...,PV.EST,American Samoa,ASM,..,1.08068346977234,1.15167808532715,1.15855598449707,1.18432366847992,1.16629731655121,1.1449339389801,1.09020864963531,1.0668408870697,1.12317395210266,1.11422121524811
4,Political Stability and Absence of Violence/Te...,PV.EST,Andorra,AND,1.16698145866394,1.28659331798553,1.36598539352417,1.38275027275085,1.39288973808289,1.39124858379364,1.57736670970917,1.58867537975311,1.58125936985016,1.58598840236664,1.58346593379974

In [4]:
data_stability.shape

(219, 15)

In [5]:
#Verification de type des variables
data_stability.dtypes

Series Name      object
Series Code      object
Country Name     object
Country Code     object
2000 [YR2000]    object
2014 [YR2014]    object
2015 [YR2015]    object
2016 [YR2016]    object
2017 [YR2017]    object
2018 [YR2018]    object
2019 [YR2019]    object
2020 [YR2020]    object
2021 [YR2021]    object
2022 [YR2022]    object
2023 [YR2023]    object
dtype: object

In [6]:
#vérification des valeurs manquantes
print(data_stability.isnull().sum())

Series Name      3
Series Code      5
Country Name     5
Country Code     5
2000 [YR2000]    5
2014 [YR2014]    5
2015 [YR2015]    5
2016 [YR2016]    5
2017 [YR2017]    5
2018 [YR2018]    5
2019 [YR2019]    5
2020 [YR2020]    5
2021 [YR2021]    5
2022 [YR2022]    5
2023 [YR2023]    5
dtype: int64

In [7]:
#Détail des valeurs manquantes pour la Country Name
data_stability.loc[data_stability['Country Name'].isnull(),:]

,Series Name,Series Code,Country Name,Country Code,2000 [YR2000],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,Data from database: Worldwide Governance Indic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,Last Updated: 11/05/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#Suppression des lignes ayant Country Name null
data_stability = data_stability.drop(index=[214,215,216,217,218])

In [9]:
import re
#Copie du dataframe data_stability
data_political_stability = data_stability.copy()

#détecter les colonnes année (ex : 2000 [YR2000])
year_cols = [c for c in data_political_stability.columns if re.search(r'\b\d{4}\b', str(c))]
pd.set_option('future.no_silent_downcasting', True)
#normaliser placeholders en NaN (ex: '..', '', 'NA')
data_political_stability[year_cols] = data_political_stability[year_cols].replace(['..', '', 'NA', 'na', 'N/A'], np.nan)

In [10]:
import sys
sys.path.append('/content/drive/MyDrive/Colab Notebooks')

In [12]:
import importlib
import Parcourir

importlib.reload(Parcourir)

In [13]:
 #remplissage des valeurs .. en 2023 par la valeur la plus récente
data_political_stability['2023 [YR2023]'] = data_political_stability[year_cols].apply(Parcourir.last_valid_value_from_right, axis=1)
data_political_stability

,Series Name,Series Code,Country Name,Country Code,2000 [YR2000],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Political Stability and Absence of Violence/Te...,PV.EST,Afghanistan,AFG,-2.43896889686584,-2.41106843948364,-2.56262516975403,-2.6621561050415,-2.7949755191803,-2.75344133377075,-2.65253973007202,-2.702721118927,-2.51867604255676,-2.54495596885681,-2.48408055305481
1,Political Stability and Absence of Violence/Te...,PV.EST,Albania,ALB,-0.539989590644836,0.485986232757568,0.341639041900635,0.337447881698608,0.373770743608475,0.366779267787933,0.11010505259037,0.0886125192046165,0.196371927857399,0.106261312961578,0.183348968625069
2,Political Stability and Absence of Violence/Te...,PV.EST,Algeria,DZA,-1.43257737159729,-1.19053518772125,-1.09078657627106,-1.09974193572998,-0.919614315032959,-0.842107713222504,-1.05585384368896,-0.847820401191711,-0.992457151412964,-0.650652348995209,-0.577885270118713
3,Political Stability and Absence of Violence/Te...,PV.EST,American Samoa,ASM,NaN,1.08068346977234,1.15167808532715,1.15855598449707,1.18432366847992,1.16629731655121,1.1449339389801,1.09020864963531,1.0668408870697,1.12317395210266,1.11422121524811
4,Political Stability and Absence of Violence/Te...,PV.EST,Andorra,AND,1.16698145866394,1.28659331798553,1.36598539352417,1.38275027275085,1.39288973808289,1.39124858379364,1.57736670970917,1.58867537975311,1.58125936985016,1.58598840236664,1.58346593379974
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,Political Stability and Absence of Violence/Te...,PV.EST,Virgin Islands (U.S.),VIR,NaN,1.16425490379333,1.22000181674957,0.975613653659821,0.981490910053253,0.956182777881622,1.05151903629303,1.00344228744507,0.47629314661026,0.529783725738525,0.534723103046417
210,Political Stability and Absence of Violence/Te...,PV.EST,West Bank and Gaza,PSE,-1.57441258430481,-1.98501086235046,-2.1540961265564,-1.97087836265564,-1.65064632892609,-1.80487740039825,-1.88942885398865,-2.01823925971985,-1.83692336082458,-1.70195543766022,-1.86521852016449
211,Political Stability and Absence of Violence/Te...,PV.EST,"Yemen, Rep.",YEM,-1.14544129371643,-2.66557502746582,-2.66801619529724,-2.78448867797852,-2.93431735038757,-2.99623465538025,-2.77101445198059,-2.64773344993591,-2.5804603099823,-2.462735414505,-2.56293869018555
212,Political Stability and Absence of Violence/Te...,PV.EST,Zambia,ZMB,0.0357203297317028,0.156212016940117,0.144709780812263,0.132928282022476,0.142043307423592,0.0826330557465553,-0.116989657282829,-0.13097919523716,0.0524137951433659,0.161331877112389,0.201727285981178
213,Political Stability and Absence of Violence/Te...,PV.EST,Zimbabwe,ZWE,-1.31881785392761,-0.713570177555084,-0.619207262992859,-0.620809733867645,-0.710430860519409,-0.721012055873871,-0.943302512168884,-1.05274343490601,-0.954442739486694,-0.894974112510681,-0.934447467327118

In [14]:
# indice_stabilite qui prend les valeurs de la colonne 2023 [YR2023]
data_political_stability['indice_stabilite'] = data_political_stability['2023 [YR2023]']

#nouveau dataframe avec 3 variable : Country Name, Country Code et indice_stabilite
variables_stability = ['Country Name','Country Code','indice_stabilite']
data_political = data_political_stability[variables_stability]

# Renommage des colonnes
data_political = data_political.rename(columns={'Country Name': 'Zone'})

# Conversion de la colonne indice_stabilie en numerique
data_political['indice_stabilite'] = pd.to_numeric(data_political['indice_stabilite'], errors='coerce')

# Arrondi des valeurs de l'indice de stabilite à 2 décimales
data_political['indice_stabilite'] = round(data_political['indice_stabilite'],2)

data_political.head()

             Zone Country Code  indice_stabilite
0     Afghanistan          AFG             -2.48
1         Albania          ALB              0.18
2         Algeria          DZA             -0.58
3  American Samoa          ASM              1.11
4         Andorra          AND              1.58

In [15]:
#vérification des valeurs manquantes
print(data_political.isnull().sum())

Zone                0
Country Code        0
indice_stabilite    1
dtype: int64

In [16]:
#Vérification des Doublons
data_political.loc[data_political[['Zone','Country Code','indice_stabilite']].duplicated(keep=False),:]

Empty DataFrame
Columns: [Zone, Country Code, indice_stabilite]
Index: []

In [17]:
#Verification s'il y a des outliers
data_political.describe()

       indice_stabilite
count        213.000000
mean           0.005915
std            1.001768
min           -2.750000
25%           -0.510000
50%            0.140000
75%            0.810000
max            1.740000

In [18]:
#préparation de l'export du dataframe en fichier CSV

data_political.to_csv('/content/drive/MyDrive/Colab Notebooks/Stabilite_Politique.csv', index=False)